name: Capture Repo Count Metric

on:
  schedule:
    - cron: "0 8 * * *" # Every day at 8am UTC
  push:
    branches: [snap-repo-metric]

jobs:
  capture:
    runs-on: ubuntu-20.04

    steps:
      - name: Get Repo Count
        uses: actions/github-script@v6
        id: repo-count
        with:
          github-token: ${{ secrets.MACHINE_TOKEN }}
          script: |
            const writeFileAsync = require("util").promisify(require("fs").writeFile);
            const repos = await github.paginate("GET /orgs/searchspring-implementations/repos", {
              per_page: 100
            }).filter(repo => !repo.name.match(/\.test$/));
            const now = new Date();
            const obj = { "timestamp": now, "type": "snap-num-repos", data: { count: repos.length } };
            const filename = `SnapNumRepos-${now.getFullYear()}_${now.getMonth() + 1}_${now.getDate()}_${now.getHours()}${now.getMinutes()}.json`;
            const contents = JSON.stringify(obj);
            await writeFileAsync(filename, contents);
            console.log("Created", filename, "with contents", contents);
            return filename;
          result-encoding: string
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.SNAPFU_AWS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.SNAPFU_AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Copy Files to S3
        shell: bash
        run: |
          aws s3 cp ./${{ steps.repo-count.outputs.result }} s3://datawarehouse-stage/team-metrics-import/${{ steps.repo-count.outputs.result }} --region us-east-1
